# Usar uma imagem base do Python
FROM python:3.8-slim

# Definir o diretório de trabalho no contêiner
WORKDIR /app

# Copiar o script para o contêiner
COPY send.py .

# Instalar a biblioteca pika
RUN pip install pika

# Comando para executar o script
CMD ["python", "send.py"]
